;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat %CMDER_ROOT%\config\.history
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
gb=git branch
gba=git branch -a $1
gcb=git checkout -b $1
gco=git checkout $1
gc=git commit $*
ga=git add $*
gl=git log --oneline --all --graph --decorate  $*
glog=git log --oneline --decorate --graph
gloga=git log --oneline --decorate --graph --all
glol=f:\scripts\glol.bat $1
gst=git status
gup=git pull --rebase
ll=ls -alL